### ISSUE TITLE
Duplicate player names

### ISSUE THREAD

**Issue by M-Yankov** [TeamGameFifteen1-Telerik/GameFifteen#17]
When entering name for scoreboard, first, check for existence of this name

**Comment by datavelizar** [comment]
Isn't it normal behavior? Same player has different results or even up to 4 top same results(from different games).

**Comment by M-Yankov** [comment]
OK I agree with you, but for me it's little confusing :confused:

**Comment by datavelizar** [comment]
If one is good enough to have top 4 results - one has the right to put his name on the first 4 places :smile:
Maybe the confusion comes by the fact that 2 different players are allowed to enter the same name. So what we might need is a registration module for the game where no duplicate accounts are allowed...
Another solution could be to check for the existence of the name to be entered and warn the player that such name already exists asking him whether he still wishes to enter this (already existing) name.
