### ISSUE TITLE
Fix Shufle when starting a new game

### ISSUE THREAD

**Issue by M-Yankov** [TeamGameFifteen1-Telerik/GameFifteen#18]
Most of numbers are already at it's places

**Comment by datavelizar** [comment]
Shuffling relies on a random number between two constants in StandartGameInitializer class: 

const int MinRoundsCount = 20;
const int MaxRoundsCount = 50;

If we increase the rounds of shuffling the probability of harder game may increase, but still there is no guarantee.

**Comment by M-Yankov** [comment]
const int MinRoundsCount = 1120;
const int MaxRoundsCount = 1150;
